login API 완료
wecode-bootcamp-korea/36-2nd-WENABADA-backend pull request #3
Opened 2022-09-01 03:44 UTC by Mjj4682

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 카카오 API를 통한 소셜 로그인 기능 구현하였습니다.

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 카카오 로그인
- 카카오에서 받은 id를 데이터베이스에 저장했습니다.
2. 세션 활용
- passport.js를 사용하여 세션을 사용했습니다. 세션에 유저 정보를 담고 세션 정보를 통해 어느 라우터에서든 유저를 확인할 수 있게 만들었습니다.
3. 로그아웃 기능을 만들었습니다.

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 1차때 사용했던 로컬 스토리지와 다르게 이번에는 세션을 사용하여 세선을 알게되었습니다.

<br />

## :: 기타 질문 및 특이 사항
- 최대한 만들어봤는데 기능상으로는 이상 없는거 같은데 잘 만든건지 모르겠습니다..

2022-09-01 05:54 UTC, kyeongraekim requested changes

2022-09-01 05:54 UTC, kyeongraekim commented on routes/index.js
> +router.get('/test', function(req, res) {
깃헙에 올라오는 코드에는 local test 용 코드는 포함되어서는 안됩니다. 해당 내용 삭제해주세요~

2022-09-01 05:54 UTC, kyeongraekim commented on routes/auth.js
> +passport.use('kakao', new KakaoStrategy({
현재 passport의 힘을 빌려 소셜로그인 인증-인가를 구현해주셨는데, 해당 라이브러리의 도움 없이 동일한 기능을 직접 구현해보실 수 있을까요?

2022-09-01 05:54 UTC, kyeongraekim commented on routes/auth.js
> +passport.use('kakao', new KakaoStrategy({
목적은 소셜로그인 oauth 절차를 보다 깊게 이해하기 위함입니다~

2022-09-01 10:29 UTC, Mjj4682 commented on routes/index.js
> +router.get('/test', function(req, res) {
수정했습니다!

2022-09-01 10:29 UTC, Mjj4682 commented on routes/auth.js
> +passport.use('kakao', new KakaoStrategy({
수정했습니다!

2022-09-02 01:32 UTC, Mjj4682 commented
백엔드에서 모든 인증을 다 하는 방식에서 백엔드는 유저 정보만 조회하는 로직으로 변경했습니다.
그리고 session으로 관리하는 방식에서 백엔드에서 토근을 프론트에 전달해주면 프론트에서 토큰으로 로컬스토리지에 저장하는 방식으로 로직을 변경했습니다.

2022-09-02 04:16 UTC, kyeongraekim commented
리베이스 진행해주세요 정진ㄴㅁ!~

2022-09-02 04:20 UTC, kyeongraekim requested changes
전반적으로 잘 진행해주셨네요. 아래 마이너 사항들 반영하고 리베이스 해주신 후에 다시 푸시해주세요!~

2022-09-02 04:20 UTC, kyeongraekim commented on middlewares/auth.js
> +		const token = await req.headers.authorization;
indentation 한 번 신경써 주세요!~ git add 전에 git diff 찍어보시면 실제 코드가 어떻게 올라가는지 터미널 상에서 확인해 볼 수 있습니다~

2022-09-02 04:20 UTC, kyeongraekim commented on package.json
>    },
기획 변경으로 인해서 삭제된 패키지 또한 dependency list에 수정한 내역대로 다시 반영해주세요!~

2022-09-02 05:18 UTC, Mjj4682 commented on middlewares/auth.js
> +		const token = await req.headers.authorization;
수정했습니다!

2022-09-02 05:18 UTC, Mjj4682 commented on package.json
>    },
수정했습니다!

2022-09-02 06:41 UTC, kyeongraekim approved these changes
LGTM!~ 다음 유저 브랜치에서 꼭 유닛테스트 같이 올려주세요~

2022-09-02 06:41 UTC, merged